import type { SocioItem } from './types';

export const mockCompanyMembers: SocioItem[] = [
	{
		id: 'socio-001',
		id_empresa: 'empresa-demo-001',
		nombre_de_socio: 'Ana Sofia Martinez',
		correo: 'ana.martinez@example.com',
		tipo_de_socio: 'Individual',
		porcentaje: 40,
		pais_de_nacionalidad: 'Mexico',
		estado_civil: 'Soltera',
		residente_fiscal: 'Si',
		numero_de_pasaporte: 'XH1234567',
		numero_de_seguro_social: null,
		numero_itin: '912-34-5678',
		direccion_planilla: '1201 Brickell Ave, Miami, FL',
		roles: ['Managing Member'],
	},
	{
		id: 'socio-002',
		id_empresa: 'empresa-demo-001',
		nombre_de_socio: 'Carlos Eduardo Rivas',
		correo: 'carlos.rivas@example.com',
		tipo_de_socio: 'Individual',
		porcentaje: 35,
		pais_de_nacionalidad: 'Colombia',
		estado_civil: 'Casado',
		residente_fiscal: 'No',
		numero_de_pasaporte: 'PA9988776',
		numero_de_seguro_social: null,
		numero_itin: null,
		direccion_planilla: '742 Evergreen Ter, Springfield',
		roles: ['Member'],
	},
	{
		id: 'socio-003',
		id_empresa: 'empresa-demo-001',
		nombre_de_socio: 'Blue Harbor Ventures LLC',
		correo: 'legal@blueharbor.example',
		tipo_de_socio: 'Entidad',
		porcentaje: 25,
		pais_de_nacionalidad: 'United States',
		estado_civil: null,
		residente_fiscal: 'Si',
		numero_de_pasaporte: null,
		numero_de_seguro_social: null,
		numero_itin: null,
		direccion_planilla: 'Delaware Registered Office',
		roles: ['Investor'],
	},
	{
		id: 'socio-004',
		id_empresa: 'empresa-demo-001',
		nombre_de_socio: null,
		correo: null,
		tipo_de_socio: null,
		porcentaje: null,
		pais_de_nacionalidad: null,
		estado_civil: null,
		residente_fiscal: null,
		numero_de_pasaporte: null,
		numero_de_seguro_social: null,
		numero_itin: null,
		direccion_planilla: null,
		roles: null,
	},
];
