-- ============================================================
-- IRS Activity Codes - Schema + Seed
-- 19 sectors | 60 categories | 316 activities
-- ============================================================

-- Drop old actividades table (replaced by sector/category/activity)
-- ALTER TABLE empresas_incorporaciones DROP CONSTRAINT IF EXISTS empresas_incorporaciones_activity_id_fkey;
-- DROP TABLE IF EXISTS actividades CASCADE;

-- Table: sector
CREATE TABLE IF NOT EXISTS sector (
    id          SERIAL          PRIMARY KEY,
    name        VARCHAR(255)    NOT NULL,
    name_en     VARCHAR(255)    NOT NULL,
    created_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Table: category
CREATE TABLE IF NOT EXISTS category (
    id          SERIAL          PRIMARY KEY,
    sector_id   INTEGER         NOT NULL REFERENCES sector(id),
    name        VARCHAR(255)    NOT NULL,
    name_en     VARCHAR(255)    NOT NULL DEFAULT '',
    created_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_category_sector_id ON category(sector_id);

-- Table: activity
CREATE TABLE IF NOT EXISTS activity (
    id              SERIAL          PRIMARY KEY,
    category_id     INTEGER         NOT NULL REFERENCES category(id),
    irs_code        VARCHAR(20)     NOT NULL UNIQUE,
    name_es         VARCHAR(500)    NOT NULL,
    name_en         VARCHAR(500)    NOT NULL DEFAULT '',
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_activity_category_id ON activity(category_id);
CREATE INDEX IF NOT EXISTS idx_activity_irs_code    ON activity(irs_code);

-- ---- Sector data ----
INSERT INTO sector (id, name, name_en) VALUES
  (1, 'Alojamiento, Servicios de Alimentos y Lugares para Beber', 'Accommodation, Food Services, and Drinking Places'),
  (2, 'Administración y Apoyo, Central de Desechos y Servicios de Reparación', 'Administrative, Support, Waste, and Remediation Services'),
  (3, 'Agricultura, Silvicultura, Caza y Pesca', 'Agriculture, Forestry, Hunting, and Fishing'),
  (4, 'Artes, Entretenimiento y Recreación', 'Arts, Entertainment, and Recreation'),
  (5, 'Construcción', 'Construction'),
  (6, 'Servicios Educativos', 'Educational Services'),
  (7, 'Financieros y de Seguros', 'Finance and Insurance'),
  (8, 'Cuidados de Salud y Asistencia Social', 'Health Care and Social Assistance'),
  (9, 'Información', 'Information'),
  (10, 'Manufactura', 'Manufacturing'),
  (11, 'Minería', 'Mining'),
  (12, 'Otros Servicios', 'Other Services'),
  (13, 'Servicios Profesionales, Científicos y Técnicos', 'Professional, Scientific, and Technical Services'),
  (14, 'Bienes Raices, Alquiler y Arrendamiento', 'Real Estate, Rental, and Leasing'),
  (15, 'Organizaciones Religiosas, Becarias, Cívicas, Profesionales y Similares', 'Religious, Grantmaking, Civic, Professional, and Similar Organizations'),
  (16, 'Comercio al Por Menor', 'Retail Trade'),
  (17, 'Transporte y Almacén', 'Transportation and Warehousing'),
  (18, 'Utilidades', 'Utilities'),
  (19, 'Comercio al Por Mayor', 'Wholesale Trade');

-- ---- Category data ----
INSERT INTO category (id, sector_id, name, name_en) VALUES
  (1, 1, 'Alojamiento', ''),
  (2, 1, 'Servicios de Alimentos y Lugares para Beber', ''),
  (3, 2, 'Servicios de Administración y Apoyo', ''),
  (4, 2, 'Control de Desechos y Servicios de Reparación', ''),
  (5, 3, 'Agricultura, Silvicultura, Caza y Pesca', 'Agriculture, Forestry, Hunting, and Fishing'),
  (6, 3, 'Actividades de Apoyo para la Agricultura y la Silvicultura', ''),
  (7, 4, 'Industrias de Entretenimiento, Apuestas y Recreación', ''),
  (8, 4, 'Museos, Lugares Históricos e Instituciones Similares', ''),
  (9, 4, 'Representación de las Artes, Deportes con Espectadores e Industrias Relacionadas', ''),
  (10, 5, 'Construcción', 'Construction'),
  (11, 5, 'Construcciones de Ingeniería Civil u Obra Pesada', ''),
  (12, 5, 'Contratistas de Trabajos Especializados para la Construcción', ''),
  (13, 6, 'Servicios Educativos', 'Educational Services'),
  (14, 7, 'Intermediación de Crédito y Actividades Relacionadas', ''),
  (15, 7, 'Compañías de Seguros y Actividades Relacionadas', ''),
  (16, 7, 'Acciones y Bonos, Contratos de Mercancías, y Otra Intermediación y Corredores', ''),
  (17, 8, 'Servicios de Cuidados de Salud Ambulatorios', ''),
  (18, 8, 'Hospitales', ''),
  (19, 8, 'Residencias de Asistencia Social y para la Salud', ''),
  (20, 8, 'Servicios de Asistencia Social', ''),
  (21, 9, 'Información', 'Information'),
  (22, 9, 'Difusión y Telecomunicaciones (excepto el Internet)', ''),
  (23, 9, 'Servicios de Información y Procesamiento de Datos', ''),
  (24, 9, 'Industrias Cinematográficas y Discográficas', ''),
  (25, 10, 'Manufactura', 'Manufacturing'),
  (26, 10, 'Manufactura de Químicos', ''),
  (27, 10, 'Manufactura de Alimentos', ''),
  (28, 10, 'Manufactura de Productos de Cuero y Aliado', ''),
  (29, 10, 'Manufactura de Productos de Minerales No Metálicos', ''),
  (30, 11, 'Minería', 'Mining'),
  (31, 12, 'Servicios Personales y de Lavandería', ''),
  (32, 12, 'Reparación y Mantenimiento', ''),
  (33, 13, 'Servicios Profesionales, Científicos y Técnicos', 'Professional, Scientific, and Technical Services'),
  (34, 13, 'Servicios Arquitectónicos de Ingeniería y Servicios Relacionados', ''),
  (35, 13, 'Servicios de Diseños de Sistemas de Computadoras y Servicios Relacionados', ''),
  (36, 13, 'Servicios de Diseños Especializados', ''),
  (37, 13, 'Otros Servicios Profesionales, Científicos y Técnicos', ''),
  (38, 14, 'Bienes Raices', ''),
  (39, 14, 'Servicios de Alquiler y Arrendamiento', ''),
  (40, 15, 'Organizaciones Religiosas, Becarias, Cívicas, Profesionales y Similares', 'Religious, Grantmaking, Civic, Professional, and Similar Organizations'),
  (41, 16, 'Concesionarios de Materiales de Construcción y Equipos y Suministros de Jardín', ''),
  (42, 16, 'Tiendas de Ropa y Accesorios de Vestir', ''),
  (43, 16, 'Tiendas de Electrónicos y Electrodomésticos', ''),
  (44, 16, 'Tiendas de Bebidas y Alimentos', ''),
  (45, 16, 'Mueblerías y Mobiliario para el Hogar', ''),
  (46, 16, 'Estaciones de Gasolina', ''),
  (47, 16, 'Tiendas de Mercancía General', ''),
  (48, 16, 'Tiendas de Cuidado Personal y Salud', ''),
  (49, 16, 'Concesionarios de Vehículos Motores y Partes', ''),
  (50, 16, 'Tiendas de Artículos Deportivos, Hobbies, Librerías y Música', ''),
  (51, 16, 'Tiendas al Por Menor de Misceláneos', ''),
  (52, 16, 'Ventas al Por Menor que No Son Tiendas', ''),
  (53, 17, 'Transporte y Almacén', 'Transportation and Warehousing'),
  (54, 17, 'Correo y Mensajeros b', ''),
  (55, 17, 'Almacén y Depósito', ''),
  (56, 18, 'Utilidades', 'Utilities'),
  (57, 19, 'Comercio al Por Mayor, Bienes Duraderos', ''),
  (58, 19, 'Comercio al Por Mayor de Bienes No Duraderos', ''),
  (59, 19, 'Mercados Electrónicos entre Negocios y Agentes y Corredores', ''),
  (60, 19, 'Establecimientos No Clasificados', '');

-- ---- Activity data ----
INSERT INTO activity (id, category_id, irs_code, name_es, name_en) VALUES
  (1, 1, '721310', 'Pensiones', 'Pension'),
  (2, 1, '721210', 'RV (vehículos recreacionales) parques y campos recreacionales', 'RV (recreational vehicles) parks and recreational fields'),
  (3, 1, '721100', 'Servicios de alojamiento temporal (incluyendo hoteles, moteles y posadas con camas y desayuno)', 'Temporary lodging services (including hotels, motels, and inns with beds and breakfasts)'),
  (4, 2, '722514', 'Cafeterías y buffets', 'Cafeterias and buffets'),
  (5, 2, '722410', 'Lugares para beber (bebidas alcohólicas)', 'Places to drink (alcoholic beverages)'),
  (6, 2, '722511', 'Restaurantes de servicio completo', 'Full-Service Restaurants'),
  (7, 2, '722513', 'Restaurantes para comer con servicio limitado', 'Restaurants to eat with limited service'),
  (8, 2, '722515', 'Bares de botanas y bebidas no alcohólicas', 'Snack and non-alcoholic beverage bars'),
  (9, 2, '722300', 'Servicios especiales de alimentos (incluyendo contratistas de servicios de alimentos y catering)', 'Special food services (including food service and catering contractors)'),
  (10, 3, '561430', 'Centros de servicios a los negocios (incluyendo centros de correos privados y tiendas de copiado)', 'Business service centers (including private post centers and copy shops)'),
  (11, 3, '561740', 'Servicios de limpieza de alfombras y tapicería', 'Carpet and upholstery cleaning services'),
  (12, 3, '561440', 'Agencias de cobranza', 'Collection agencies'),
  (13, 3, '561450', 'Oficinas de crédito', 'Credit Bureaus'),
  (14, 3, '561410', 'Servicios de preparación de documentos', 'Document Preparation Services'),
  (15, 3, '561300', 'Servicios de empleo', 'Employment Services'),
  (16, 3, '561710', 'Servicios de control de plagas y exterminio', 'Pest Control & Extermination Services'),
  (17, 3, '561210', 'Servicios de apoyo a las instalaciones', 'Facility Support Services'),
  (18, 3, '561600', 'Servicios de seguridad e investigaciones', 'Security and Investigations Services'),
  (19, 3, '561720', 'Servicios de limpieza', 'Cleaning services'),
  (20, 3, '561730', 'Servicios de jardinería ornamental', 'Ornamental Landscaping Services'),
  (21, 3, '561110', 'Oficina de servicios administrativos', 'Office of Administrative Services'),
  (22, 3, '561420', 'Centros de llamadas telefónicas', 'Call Centers'),
  (23, 3, '561500', 'Agencias de viaje y servicios de reservaciones', 'Travel agencies and reservation services'),
  (24, 3, '561490', 'Otros servicios de apoyo a los negocios (incluyendo servicios de reposeción, informes para las cortes, y servicios de taquigrafía)', 'Other business support services (including repossession services, court reports, and shorthand services)'),
  (25, 3, '561790', 'Otros servicios a los edificios y viviendas', 'Other services to buildings and homes'),
  (26, 3, '561900', 'Otros servicios de apoyo (incluyendo servicios de empaque y etiquetado, yorganizadores de exposiciones para convenciones y exhibiciones de intercambio)', 'Other support services (including packaging and labeling services, and exhibition organizers for conventions and exchange exhibitions)'),
  (27, 4, '562000', 'Control de desechos y servicios de reparación', 'Scrap Control & Repair Services'),
  (28, 5, '112900', 'Producción de otros animales (incluyendo cría de gatos y perros)', 'Production of other animals (including cat and dog breeding)'),
  (29, 5, '114110', 'Pesca', 'Fishing'),
  (30, 5, '113000', 'Silvicultura y aserraderos', 'Forestry and sawmills'),
  (31, 5, '114210', 'Caza y caza con trampas', 'Hunting and Trap Hunting'),
  (32, 6, '115210', 'Actividades de apoyo para la producción de animales', 'Support activities for animal production'),
  (33, 6, '115110', 'Actividades de apoyo para la producción de cosechas (incluyendo desmotadora de algodón, preparación del suelo, siembra y cultivo)', 'Support activities for crop production (including cotton ginning, soil preparation, planting and cultivation)'),
  (34, 6, '115310', 'Actividades de apoyo para la silvicultura', 'Forestry support activities'),
  (35, 7, '713100', 'Parques de diversiones y salones de juego', 'Amusement parks and arcades'),
  (36, 7, '713200', 'Industrias de apuestas', 'Betting Industries'),
  (37, 7, '713900', 'Otras industrias de diversión y recreación (incluyendo campos de golf, instalaciones para esquiar, marinas, centros de salud física y boliche)', 'Other amusement and recreation industries (including golf courses, ski facilities, marinas, fitness centers, and bowling)'),
  (38, 8, '712100', 'Museos, lugares históricos e instituciones similares', 'Museums, historic sites, and similar institutions'),
  (39, 9, '711410', 'Agentes y administradores para los artistas, atletas, y otras figuras públicas', 'Agents and administrators for artists, athletes, and other public figures'),
  (40, 9, '711510', 'Artistas, escritores y representantes de las artes independientes', 'Artists, writers and representatives of the independent arts'),
  (41, 9, '711100', 'Compañías de representación de las artes', 'Arts Representation Companies'),
  (42, 9, '711300', 'Promotores de la representación de las artes, deportes y eventos similares', 'Promoters of the representation of arts, sports and similar events'),
  (43, 9, '711210', 'Deportes con espectadores (incluyendo los clubes de deportes y las pistas de carreras)', 'Spectator sports (including sports clubs and racetracks)'),
  (44, 10, '236200', 'Construcción de edificios no residenciales', 'Construction of non-residential buildings'),
  (45, 10, '236100', 'Construcción de edificios residenciales', 'Construction of residential buildings'),
  (46, 11, '237310', 'Construcción de autopistas, calles, puentes y túneles', 'Construction of highways, streets, bridges and tunnels'),
  (47, 11, '237210', 'Sub-división de tierras y desarrollo de tierras', 'Land Subdivision and Land Development'),
  (48, 11, '237100', 'Contratistas de plomería, calefacción y aire acondicionado', 'Plumbing, heating, and air conditioning contractors'),
  (49, 11, '237990', 'Otras construcciones de ingeniería civil u obra pesada', 'Other civil engineering or heavy construction'),
  (50, 12, '238310', 'Contratistas para colocación de muros falsos y aislamiento', 'Contractors for laying false walls and insulation'),
  (51, 12, '238210', 'Contratistas electricistas', 'Electrical Contractors'),
  (52, 12, '238350', 'Contratistas para trabajos de acabados en edificaciones', 'Building Finishing Contractors'),
  (53, 12, '238330', 'Contratistas para colocación de pisos flexibles y de maderas', 'Contractors for laying flexible floors and wood'),
  (54, 12, '238130', 'Contratistas para instalación de productos de carpintería', 'Contractors for the installation of woodworking products'),
  (55, 12, '238150', 'Contratistas para instalación de vidrios y cerámica', 'Glass and Ceramic Installation Contractors'),
  (56, 12, '238140', 'Contratistas de albañilería', 'Masonry Contractors'),
  (57, 12, '238320', 'Contratistas de pintura y cobertura de paredes', 'Painting and Wall Covering Contractors'),
  (58, 12, '238220', 'Contratistas de instalaciones hidrosanitarias, de gas, aire acondicionado y calefacción', 'Contractors for hydrosanitary, gas, air conditioning and heating installations'),
  (59, 12, '238110', 'Contratistas de concreto', 'Concrete Contractors'),
  (60, 12, '238160', 'Contratistas para colocar techos', 'Roofing contractors'),
  (61, 12, '238170', 'Contratistas para colocar tablas de forro y láminas de metal', 'Contractors for laying liner boards and sheet metal'),
  (62, 12, '238910', 'Contratistas de preparación de terrenos para la construcción', 'Construction Site Preparation Contractors'),
  (63, 12, '238120', 'Contratistas para montaje de estructuras prefabricadas', 'Contractors for the assembly of prefabricated structures'),
  (64, 12, '238340', 'Contratistas para colocación de pisos cerámicos y azulejos', 'Contractors for laying ceramic floors and tiles'),
  (65, 12, '238290', 'Contratistas de otras instalaciones y equipamiento en construcciones', 'Contractors of other installations and equipment in constructions'),
  (66, 12, '238390', 'Contratistas para otros trabajos de acabados en edificaciones', 'Contractors for other building finishing work'),
  (67, 12, '238190', 'Contratistas de otros trabajos en exteriores', 'Other Outdoor Contractors'),
  (68, 12, '238990', 'Contratistas de otros trabajos especializados para la construcción', 'Other Specialty Construction Contractors'),
  (69, 13, '611000', 'Servicios educativos (incluyendo tecnológicos, universidades y escuelas profesionales)', 'Educational services (including technology, colleges, and career schools)'),
  (70, 14, '522100', 'Intermediación de crédito depositario', 'Intermediation of depositary credit'),
  (71, 14, '522200', 'Intermediación de crédito no depositario', 'Non-depository credit intermediation'),
  (72, 14, '522300', 'Actividades relacionadas con el crédito de intermediación (incluyendo a los corredores de préstamos)', 'Activities related to intermediation credit (including loan brokers)'),
  (73, 15, '524210', 'Corredores y agencias de seguros', 'Insurance brokers and agencies'),
  (74, 15, '524290', 'Otras actividades relacionadas con los seguros', 'Other insurance-related activities'),
  (75, 16, '523140', 'Corretaje de contratos de mercancías', 'Freight contract brokerage'),
  (76, 16, '523130', 'Manejo de contratos de mercancías', 'Handling of goods contracts'),
  (77, 16, '523110', 'Banca de inversiones y manejo de acciones y bonos', 'Investment banking and stock and bond management'),
  (78, 16, '523120', 'Corretaje de acciones y bonos', 'Stock and bond brokerage'),
  (79, 16, '523210', 'Intercambio de acciones, bonos y mercancías', 'Exchange of stocks, bonds and commodities'),
  (80, 16, '523900', 'Otras actividades de inversión financiera (incluyendo la administración de carteras y asesoría de inversión)', 'Other financial investment activities (including portfolio management and investment advisory)'),
  (81, 17, '621610', 'Servicios de cuidado de salud en el hogar', 'Home Health Care Services'),
  (82, 17, '621510', 'Laboratorios médicos y de diagnóstico', 'Medical and diagnostic laboratories'),
  (83, 17, '621310', 'Consultorios quiroprácticos', 'Chiropractic Offices'),
  (84, 17, '621210', 'Consultorios odontológicos', 'Dental Offices'),
  (85, 17, '621330', 'Consultorios de profesionales en salud mental (salvo los médicos)', 'Mental health professionals'' offices (except doctors)'),
  (86, 17, '621320', 'Consultorios oftalmológicos', 'Ophthalmology Offices'),
  (87, 17, '621340', 'Consultorios de terapeutas físicos y ocupacionales, logopedas, y audiólogos', 'Physical and occupational therapist offices, speech therapists, and audiologists'),
  (88, 17, '621111', 'Consultorios médicos (salvo los especialistas en salud mental)', 'Medical offices (except mental health specialists)'),
  (89, 17, '621112', 'Consultorios médicos, especialistas en salud mental', 'Doctors'' offices, mental health specialists'),
  (90, 17, '621391', 'Consultorios privados de nutriólogos y dietistas', 'Private practices of nutritionists and dietitians'),
  (91, 17, '621399', 'Oficinas de todos los demás profesionales de salud', 'Offices of all other health care professionals'),
  (92, 17, '621400', 'Centros de atención ambulatoria', 'Outpatient care facilities'),
  (93, 17, '621900', 'Servicios de atención ambulatoria (incluyendo servicios de ambulancia, y bancos de sangre y órganos)', 'Outpatient care services (including ambulance services, and blood and organ banks)'),
  (94, 18, '622000', 'Hospitales', 'Hospitals'),
  (95, 19, '623000', 'Instalaciones de cuidado de convalecencia y residencial', 'Convalescent and residential care facilities'),
  (96, 20, '624410', 'Servicios de cuidado infantil', 'Child Care Services'),
  (97, 20, '624200', 'Alimentación y vivienda comunitaria, y emergencia y otros servicios de auxilio', 'Food and community housing, and emergency and other relief services'),
  (98, 20, '624100', 'Servicios individuales y para la familia', 'Individual and Family Services'),
  (99, 20, '624310', 'Servicios de rehabilitación vocacional', 'Vocational Rehabilitation Services'),
  (100, 21, '511000', 'Industrias de publicación (excepto el Internet)', 'Publishing industries (except the Internet)'),
  (101, 22, '515000', 'Radio y teledifusión (excepto el Internet)', 'Radio and television broadcasting (except the Internet)'),
  (102, 22, '517000', 'Telecomunicaciones', 'Telecommunications'),
  (103, 23, '518210', 'Servicios de procesamiento de datos', 'Data Processing Services'),
  (104, 23, '51900', 'Otros servicios de información (incluyendo agencia de prensa, bibliotecas y servicios de información por Internet)', 'Other information services (including press agencies, libraries and Internet information services)'),
  (105, 24, '512100', 'Industrias cinematográficas y de video (salvo el alquiler de video)', 'Film and video industries (except video rentals)'),
  (106, 24, '512200', 'Industrias discográficas', 'Recording industries'),
  (107, 25, '315000', 'Manufactura de ropa', 'Clothing Manufacturing'),
  (108, 25, '312000', 'Manufactura de productos de bebidas y tabaco', 'Beverage and tobacco products manufacturing'),
  (109, 25, '334000', 'Manufactura de computadoras y equipos periféricos', 'Computer and peripheral equipment manufacturing'),
  (110, 25, '335000', 'Manufactura de equipos eléctricos, artefactos eléctricos y componentes', 'Manufacture of electrical equipment, electrical appliances and components'),
  (111, 25, '332000', 'Manufactura de productos de metales fabricados', 'Manufacture of fabricated metal products'),
  (112, 25, '337000', 'Manufactura de muebles y otros productos relacionados', 'Furniture and other related products manufacturing'),
  (113, 25, '333000', 'Manufactura de maquinaria', 'Machinery Manufacturing'),
  (114, 25, '339110', 'Manufactura de equipos médicos y suministros', 'Medical Equipment & Supplies Manufacturing'),
  (115, 25, '322000', 'Manufactura de papel', 'Paper manufacturing'),
  (116, 25, '324100', 'Manufactura de productos de carbón y petróleo', 'Manufacture of coal and petroleum products'),
  (117, 25, '326000', 'Manufactura de productos de plástico y goma', 'Manufacture of plastic and rubber products'),
  (118, 25, '331000', 'Manufactura de metales primarios', 'Manufacture of primary metals'),
  (119, 25, '323100', 'Imprenta y actividades de apoyo relacionadas', 'Printing and related support activities'),
  (120, 25, '313000', 'Moliendas textiles', 'Textile milling'),
  (121, 25, '314000', 'Productos de moliendas textiles', 'Textile Grinding Products'),
  (122, 25, '336000', 'Manufactura de equipos de transporte', 'Transportation Equipment Manufacturing'),
  (123, 25, '321000', 'Manufactura de productos de madera', 'Manufacture of wood products'),
  (124, 25, '339900', 'Manufactura de otros misceláneos', 'Manufacture of other miscellaneous'),
  (125, 26, '325100', 'Manufactura de químicos básicos', 'Basic Chemical Manufacturing'),
  (126, 26, '325500', 'Manufactura de pinturas, revestimientos y adhesivos', 'Manufacture of paints, coatings and adhesives'),
  (127, 26, '325300', 'Manufactura de pesticidas, fertilizantes y otros químicos para la agricultura', 'Manufacture of pesticides, fertilizers and other chemicals for agriculture'),
  (128, 26, '325410', 'Manufactura de farmacéuticos y medicinas', 'Pharmaceutical and medicine manufacturing'),
  (129, 26, '325200', 'Manufactura de resinas, goma sintética y artificial, fibras sintéticas y filamentos', 'Manufacture of resins, synthetic and artificial rubber, synthetic fibres and filaments'),
  (130, 26, '325600', 'Manufactura de jabón, compuestos de limpieza y preparación para pocetas', 'Manufacture of soap, cleaning compounds and preparation for wells'),
  (131, 26, '325900', 'Manufactura de otras preparaciones y productos químicos', 'Manufacture of other preparations and chemicals'),
  (132, 27, '311110', 'Manufactura de alimentos para animales', 'Animal feed manufacturing'),
  (133, 27, '311800', 'Panaderías y manufactura de tortillas', 'Bakeries and tortilla manufacturing'),
  (134, 27, '311500', 'Manufactura de productos lácteos', 'Dairy Manufacturing'),
  (135, 27, '311400', 'Enlatado de fruta y verdura, y manufactura de especialidades en alimentos', 'Canning of fruit and vegetables, and manufacture of specialty foods'),
  (136, 27, '311200', 'Molienda de grano y semillas oleaginosas', 'Grain and oilseed milling'),
  (137, 27, '311610', 'Matadero y procesamiento de animales', 'Animal slaughterhouse and processing'),
  (138, 27, '311710', 'Preparación y empaquetamiento de mariscos', 'Seafood Preparation and Packaging'),
  (139, 27, '311300', 'Manufactura de azúcar y productos de confitería', 'Manufacture of sugar and confectionery products'),
  (140, 27, '311900', 'Manufactura de otros alimentos (incluyendo café, te, sazones y condimentos)', 'Manufacture of other foods (including coffee, tea, seasonings, and condiments)'),
  (141, 28, '316210', 'Manufactura de zapatos (incluyendo los de goma y plástico)', 'Manufacture of shoes (including rubber and plastic)'),
  (142, 28, '316110', 'Cuero, cuero curtido y acabados', 'Leather, tanned leather and finishes'),
  (143, 28, '316990', 'Manufactura de otros productos de cuero y aliados', 'Manufacture of other leather products and allies'),
  (144, 29, '327300', 'Manufactura de productos de cemento y concreto', 'Manufacture of cement and concrete products'),
  (145, 29, '327100', 'Manufactura de productos de arcilla y refractarios', 'Manufacture of clay and refractory products'),
  (146, 29, '327210', 'Manufactura de vidrios y productos de vidrios', 'Glass and glass products manufacturing'),
  (147, 29, '327400', 'Manufactura de productos de cal y yeso', 'Manufacture of lime and gypsum products'),
  (148, 29, '327900', 'Manufactura de otros productos de minerales no metálicos', 'Manufacture of other products of non-metallic minerals'),
  (149, 30, '212110', 'Minería de carbón', 'Coal mining'),
  (150, 30, '211120', 'Extracción de petróleo crudo', 'Crude Oil Extraction'),
  (151, 30, '212200', 'Minería de minerales de metal', 'Metal Mineral Mining'),
  (152, 30, '211130', 'Extracción de petróleo crudo', 'Crude Oil Extraction'),
  (153, 30, '212300', 'Minería de minerales no metálicos', 'Mining of non-metallic minerals'),
  (154, 30, '213110', 'Actividades de apoyo para la minería', 'Support activities for mining'),
  (155, 31, '812111', 'Barberías', 'Barbershops'),
  (156, 31, '812112', 'Salones de belleza', 'Beauty salons'),
  (157, 31, '812220', 'Cementerios y crematorios', 'Cemeteries and crematoria'),
  (158, 31, '812310', 'Servicios de tintorería y lavandería que funcionan con monedas', 'Coin-operated dry cleaning and laundry services'),
  (159, 31, '812320', 'Servicios de tintorería y lavandería (exceptuando las que funcionan con monedas)', 'Dry cleaning and laundry services (except coin-operated services)'),
  (160, 31, '812210', 'Servicios de funeraria', 'Funeral Home Services'),
  (161, 31, '812330', 'Suministros de ropa blanca y uniformes', 'Linen and uniform supplies'),
  (162, 31, '812113', 'Salones de manicura', 'Nail salons'),
  (163, 31, '812930', 'Estaciones y garajes', 'Stations and garages'),
  (164, 31, '812910', 'Servicios de cuidados para mascotas (exceptuando los veterinarios)', 'Pet care services (except veterinarians)'),
  (165, 31, '812920', 'Acabado de fotografía', 'Photography Finish'),
  (166, 31, '812190', 'Otros servicios de cuidado personal (incluyendo centros dietéticos y de reducción de peso)', 'Other personal care services (including diet and weight reduction centers)'),
  (167, 31, '812990', 'Los servicios personales restantes', 'The remaining personal services'),
  (168, 32, '811120', 'Reparaciones de carrocería, pintura, interior y vidrios de automóviles', 'Car body, paint, interior and glass repairs'),
  (169, 32, '811110', 'Mecánica automotriz, reparaciones eléctricas y mantenimiento', 'Automotive mechanics, electrical repairs and maintenance'),
  (170, 32, '811190', 'Otras reparaciones y mantenimiento automotriz (incluyendo talleres de cambio de aceite y lubricación, y auto lavados)', 'Other automotive repairs and maintenance (including oil change and lubrication shops, and car washes)'),
  (171, 32, '811310', 'Reparación y mantenimiento de maquinaria y equipos comerciales e industriales (exceptuando automóviles y eléctricos)', 'Repair and maintenance of commercial and industrial machinery and equipment (except automobiles and electrical)'),
  (172, 32, '811210', 'Reparación y mantenimiento de equipos electrónicos y de precisión', 'Repair and maintenance of electronic and precision equipment'),
  (173, 32, '811430', 'Reparación de calzado y bienes de cuero', 'Repair of footwear and leather goods'),
  (174, 32, '811410', 'Reparación y mantenimiento del hogar y jardín y electrodomésticos', 'Home and garden repair and maintenance and appliances'),
  (175, 32, '811420', 'Reparación y restauración de muebles', 'Furniture repair and restoration'),
  (176, 32, '811490', 'Reparación y mantenimiento de otros bienes personales y del hogar', 'Repair and maintenance of other personal and household property'),
  (177, 33, '541100', 'Servicios legales', 'Legal Services'),
  (178, 33, '541211', 'Oficinas de contadores públicos certificados', 'Certified Public Accountant Offices'),
  (179, 33, '541214', 'Servicios de nomina', 'Payroll Services'),
  (180, 33, '541213', 'Servicios de preparación de impuestos', 'Tax Preparation Services'),
  (181, 33, '541219', 'Otros servicios contables', 'Other accounting services'),
  (182, 34, '541310', 'Servicios de arquitectos', 'Architect Services'),
  (183, 34, '541350', 'Servicios de inspección de edificios', 'Building Inspection Services'),
  (184, 34, '541340', 'Servicios de bosquejos', 'Sketching Services'),
  (185, 34, '541330', 'Servicios de ingeniería', 'Engineering Services'),
  (186, 34, '541360', 'Servicios de agrimensura y cartografía geofísica', 'Geophysical surveying and mapping services'),
  (187, 34, '541320', 'Servicios de paisajes arquitectónicos', 'Architectural Landscape Services'),
  (188, 34, '541370', 'Servicios de agrimensura y cartografía (salvo la geofísica)', 'Surveying and mapping services (except geophysics)'),
  (189, 34, '541380', 'Laboratorios de pruebas', 'Testing Labs'),
  (190, 35, '541510', 'Servicios de diseños de sistemas de computadoras y servicios relacionados', 'Computer system design and related services'),
  (191, 36, '541400', 'Servicios de diseños especializados (incluyendo el diseño interior, industrial, grafico y de modas)', 'Specialized design services (including interior, industrial, graphic and fashion design)'),
  (192, 37, '541800', 'Servicios de publicidad y servicios relacionados', 'Advertising and related services'),
  (193, 37, '541600', 'Servicios de asesoría administrativa, científica y tecnológica', 'Administrative, scientific and technological advisory services'),
  (194, 37, '541910', 'Investigación de mercadeo y encuestas de opinión publica', 'Marketing Research and Public Opinion Polls'),
  (195, 37, '541920', 'Servicios fotográficos', 'Photo Services'),
  (196, 37, '541700', 'Servicios de investigación y desarrollo científico', 'Scientific Research and Development Services'),
  (197, 37, '541930', 'Servicios de traducción e interpretación', 'Translation and interpretation services'),
  (198, 37, '541940', 'Servicios veterinarios', 'Veterinary Services'),
  (199, 37, '541990', 'Los servicios profesionales, científicos y técnicos restantes', 'The remaining professional, scientific and technical services'),
  (200, 38, '531100', 'Arrendadores de bienes raices (incluyendo los mini almacenes y bodegas personales)', 'Real estate lessors (including convenience stores and personal warehouses)'),
  (201, 38, '531210', 'Oficinas de agentes y corredores de bienes raices', 'Real Estate Agent and Broker Offices'),
  (202, 38, '531320', 'Oficinas de avaluadores de bienes raices', 'Real Estate Appraiser Offices'),
  (203, 38, '531310', 'Administradores de propiedades de bienes raices', 'Real Estate Property Managers'),
  (204, 38, '531390', 'Otras actividades relacionadas con bienes raices', 'Other Real Estate-Related Activities'),
  (205, 39, '532100', 'Alquiler y arrendamiento de equipo automotriz', 'Automotive Equipment Rental and Leasing'),
  (206, 39, '532400', 'Alquiler y arrendamiento de equipos y maquinarias industriales y comerciales', 'Rental and leasing of industrial and commercial equipment and machinery'),
  (207, 39, '532210', 'Alquiler al consumidor de artefactos electrodomesticos', 'Consumer rental of appliances'),
  (208, 39, '532281', 'Alquiler de trajes formales y disfraces', 'Formal costume and costume rental'),
  (209, 39, '532310', 'Centros de alquiler general', 'General rental centers'),
  (210, 39, '532282', 'Alquiler de discos y cintas de video', 'Rental of discs and videotapes'),
  (211, 39, '532290', 'Alquiler de otros bienes al consumidor', 'Rental of other goods to the consumer'),
  (212, 40, '813000', 'Organizaciones religiosas, becarias, cívicas, profesionales y similares', 'Religious, fellowship, civic, professional, and similar organizations'),
  (213, 41, '444130', 'Ferreterías', 'Hardware stores'),
  (214, 41, '444110', 'Centros del hogar', 'Home Centers'),
  (215, 41, '444200', 'Tiendas de equipos y suministros para el césped y el jardín', 'Lawn & Garden Equipment & Supply Stores'),
  (216, 41, '444120', 'Tiendas de pinturas y papel tapiz', 'Paint and wallpaper stores'),
  (217, 41, '444190', 'Otros concesionarios de materiales de construcción', 'Other Building Materials Dealers'),
  (218, 42, '448130', 'Tiendas de ropa para niños e infantes', 'Children''s and infants'' clothing stores'),
  (219, 42, '448150', 'Tiendas de accesorios de vestir', 'Clothing Accessory Stores'),
  (220, 42, '448140', 'Tiendas de ropa para la familia', 'Family Clothing Stores'),
  (221, 42, '448310', 'Joyerías', 'Jewelries'),
  (222, 42, '448320', 'Tiendas de equipajes y bienes de cuero', 'Luggage and leather goods shops'),
  (223, 42, '448110', 'Tiendas de ropa de caballeros', 'Men''s clothing stores'),
  (224, 42, '448210', 'Zapaterías', 'Shoes'),
  (225, 42, '448120', 'Tiendas de ropa para damas', 'Ladies'' Clothing Stores'),
  (226, 42, '448190', 'Otras tiendas de ropa', 'Other clothing stores'),
  (227, 43, '443142', 'Tiendas de electrónicos (incluyendo audio, vídeo, computadoras y cámaras)', 'Electronics stores (including audio, video, computers, and cameras)'),
  (228, 43, '443141', 'Tiendas de electrodomésticos', 'Appliance stores'),
  (229, 44, '445310', 'Licorerías', 'Liquor stores'),
  (230, 44, '445220', 'Pescaderías', 'Fishmongers'),
  (231, 44, '445230', 'Mercados de frutas y vegetales', 'Fruit and vegetable markets'),
  (232, 44, '445100', 'Grocery stores (including supermarkets & convenience stores without gas)', 'Grocery stores (including supermarkets & convenience stores without gas)'),
  (233, 44, '445210', 'Tiendas de comestibles', 'Grocery stores'),
  (234, 44, '445290', 'Todas las tiendas de especialidades de alimentos restantes', 'All remaining specialty food stores'),
  (235, 45, '442110', 'Mueblerías', 'Furniture stores'),
  (236, 45, '442200', 'Mobiliarios para el hogar', 'Home Furnishings'),
  (237, 46, '447100', 'Estaciones de gasolina (incluyendo las tiendas de comodidad)', 'Gas stations (including convenience stores)'),
  (238, 47, '452000', 'Tiendas de mercancía general', 'General merchandise stores'),
  (239, 48, '446120', 'Tiendas de cosméticos, suministros de belleza y perfumerías', 'Cosmetics, beauty supply and perfumery stores'),
  (240, 48, '446130', 'Tiendas de bienes ópticos', 'Optical goods stores'),
  (241, 48, '446110', 'Farmacias y droguerías', 'Pharmacies and drugstores'),
  (242, 48, '446190', 'Otras tiendas de cuidados personales y de salud', 'Other health and personal care stores'),
  (243, 49, '441300', 'Tiendas de partes automotores, accesorios y llantas', 'Automotive parts, accessories and tire stores'),
  (244, 49, '441222', 'Concesionario de botes', 'Boat Dealer'),
  (245, 49, '441228', 'Concesionarios de motocicletas', 'Motorcycle dealerships'),
  (246, 49, '441110', 'Concesionarios de autos nuevos', 'New Car Dealerships'),
  (247, 49, '441210', 'Concesionarios de vehículos recreacionales', 'Recreational Vehicle Dealers'),
  (248, 49, '441120', 'Concesionarios de autos usados', 'Used Car Dealerships'),
  (249, 50, '451211', 'Librerías', 'Libraries'),
  (250, 50, '451120', 'Jugueterías y tiendas de hobbies', 'Toy stores and hobby stores'),
  (251, 50, '451140', 'Tiendas de música', 'Music Stores'),
  (252, 50, '451212', 'Concesionarios de noticias y puestos de periódicos', 'News Concessionaires and Newsstands'),
  (253, 50, '451130', 'Mercerías', 'Haberdashery'),
  (254, 50, '451110', 'Tiendas de artículos deportivos', 'Sporting goods stores'),
  (255, 51, '453920', 'Concesionarios de arte', 'Art dealerships'),
  (256, 51, '453110', 'Floristerías', 'Florists'),
  (257, 51, '453220', 'Tiendas de novedades, regalos y recuerdos', 'Novelty, gift and souvenir shops'),
  (258, 51, '453930', 'Concesionarios de casas pre-fabricadas (móvil)', 'Manufactured Home Dealers (Mobile)'),
  (259, 51, '453210', 'Tiendas de suministros y papelería para oficinas', 'Office Stationery & Supply Stores'),
  (260, 51, '453910', 'Tiendas de mascotas y suministros para mascotas', 'Pet Stores & Pet Supplies'),
  (261, 51, '453310', 'Tiendas de mercancía usada', 'Used merchandise stores'),
  (262, 51, '453990', 'Todas las tiendas al por menor de misceláneos restantes (incluyendo las tabaquerías, tiendas de velas y de trofeos)', 'All remaining miscellaneous retail stores (including tobacco shops, candle and trophy stores)'),
  (263, 52, '454112', 'Subastas electrónicas', 'Electronic auctions'),
  (264, 52, '454111', 'Comercio electrónico', 'E-commerce'),
  (265, 52, '454310', 'Concesionarios de petróleo', 'Oil Dealers'),
  (266, 52, '454113', 'Casas de órdenes por correo', 'Mail Order Houses'),
  (267, 52, '454210', 'Operadores de maquinas expendedoras', 'Vending Machine Operators'),
  (268, 52, '454390', 'Otros establecimientos de ventas directas (incluyendo ventas de puerta en puerta, proveedores de planes de comidas congeladas, plan de mercancías para fiestas y proveedores de servicios para descansos para el café)', 'Other direct sales establishments (including door-to-door sales, frozen meal plan providers, party merchandise plan, and coffee break service providers)'),
  (269, 53, '481000', 'Transporte aéreo', 'Air transport'),
  (270, 53, '485510', 'Industria de los autobuses fletados', 'Chartered bus industry'),
  (271, 53, '484110', 'Flete general por transporte por camión, local', 'General freight by truck, local'),
  (272, 53, '484120', 'Flete general por transporte por camión, larga distancia', 'General freight by truck, long distance'),
  (273, 53, '485210', 'Transporte interurbano y rural por autobús', 'Intercity and rural transport by bus'),
  (274, 53, '486000', 'Transporte de ductos', 'Pipeline Transportation'),
  (275, 53, '482110', 'Transporte por ferrocarril', 'Rail transport'),
  (276, 53, '487000', 'Transporte de paseo', 'Ride Transportation'),
  (277, 53, '485410', 'Transporte escolar y de empleados por autobús', 'School and employee bus transportation'),
  (278, 53, '484200', 'Flete por transporte por camión especializado', 'Freight by specialized truck transport'),
  (279, 53, '485300', 'Servicio de taxi y limosinas', 'Taxi and limousine service'),
  (280, 53, '485110', 'Sistemas de transito urbano', 'Urban Transit Systems'),
  (281, 53, '483000', 'Transporte acuático', 'Water transport'),
  (282, 53, '485990', 'Otros transportes terrestres de transito y pasajeros', 'Other Transit and Passenger Land Transportation'),
  (283, 53, '488000', 'Actividades de apoyo al transporte (incluyendo servicio de grúa)', 'Transport support activities (including towing service)'),
  (284, 54, '492000', 'Correo y mensajeros', 'Mail and couriers'),
  (285, 55, '493100', 'Almacén y deposito (salvo los arrendadores de mini almacenes y unidades de auto almacenamiento)', 'Warehouse and warehouse (except for lessors of mini warehouses and self-storage units)'),
  (286, 56, '221000', 'Utilidades', 'Utilities'),
  (287, 57, '423200', 'Mayoristas de muebles y mobiliarios para el hogar', 'Wholesalers of furniture and home furnishings'),
  (288, 57, '423700', 'Mayoristas de ferretería, y equipos y suministros de plomería y calefacción', 'Wholesalers of hardware, and plumbing and heating equipment and supplies'),
  (289, 57, '423600', 'Mayoristas de bienes eléctricos', 'Wholesalers of electrical goods'),
  (290, 57, '423940', 'Mayoristas de joyería, relojes, piedras y metales preciosos', 'Wholesalers of jewelry, watches, stones and precious metals'),
  (291, 57, '423300', 'Mayoristas de tablas y otros materiales de construcción', 'Wholesalers of boards and other building materials'),
  (292, 57, '423800', 'Mayoristas de maquinaria, equipos y suministros', 'Wholesalers of machinery, equipment and supplies'),
  (293, 57, '423500', 'Mayoristas de metales y minerales (salvo petróleo)', 'Wholesalers of metals and minerals (except oil)'),
  (294, 57, '423100', 'Mayoristas de vehículos motores y partes para vehículos motores', 'Wholesalers of motor vehicles and parts for motor vehicles'),
  (295, 57, '423400', 'Mayoristas de equipos y suministros profesionales y comerciales', 'Professional and commercial equipment and supplies wholesalers'),
  (296, 57, '423930', 'Mayoristas de materiales reciclables', 'Recyclable Materials Wholesalers'),
  (297, 57, '423910', 'Mayoristas de bienes y suministros deportivos y recreacionales', 'Wholesalers of sports and recreational goods and supplies'),
  (298, 57, '423920', 'Mayoristas de bienes y suministros de juguetería y hobbies', 'Wholesalers of toy and hobby goods and supplies'),
  (299, 57, '423990', 'Mayoristas de otros bienes duraderos misceláneos', 'Wholesalers of other miscellaneous durable goods'),
  (300, 58, '424300', 'Mayoristas de ropa, bienes en piezas y nociones', 'Wholesalers of clothing, goods in pieces and notions'),
  (301, 58, '424800', 'Mayoristas de licores', 'Liquor wholesalers'),
  (302, 58, '424920', 'Mayoristas de libros, revistas y periódicos', 'Wholesalers of books, magazines and newspapers'),
  (303, 58, '424600', 'Mayoristas de químicos y productos aliados', 'Wholesalers of chemicals and allied products'),
  (304, 58, '424210', 'Mayoristas de medicinas, drogas y artículos diversos', 'Wholesalers of medicines, drugs and miscellaneous items'),
  (305, 58, '424500', 'Mayoristas de productos de granja de materiales crudos', 'Wholesalers of Raw Material Farm Products'),
  (306, 58, '424910', 'Mayoristas de suministros para granjas', 'Farm Supplies Wholesalers'),
  (307, 58, '424930', 'Mayoristas de flores, surtidos de viveros y suministros para floristerías', 'Flower wholesalers, nursery assortments, and florist supplies'),
  (308, 58, '424400', 'Mayoristas de comestibles y productos relacionados', 'Wholesalers of groceries and related products'),
  (309, 58, '424950', 'Mayoristas de pintura, barniz y suministros', 'Paint, Varnish & Supplies Wholesalers'),
  (310, 58, '424100', 'Mayoristas de papel y productos de papel', 'Wholesalers of paper and paper products'),
  (311, 58, '424700', 'Mayoristas de petróleo y suministros del petróleo', 'Oil wholesalers and oil supplies'),
  (312, 58, '424940', 'Mayoristas de tabaco y productos del tabaco', 'Tobacco and tobacco products wholesalers'),
  (313, 58, '424990', 'Mayoristas de otros bienes no duraderos misceláneos', 'Wholesalers of other miscellaneous non-durable goods'),
  (314, 59, '425110', 'Mercados electrónicos entre negocios', 'Electronic marketplaces between businesses'),
  (315, 59, '425120', 'Agentes y corredores que actúan como intermediarios en la distribución de mercancía al por mayor', 'Agents and brokers who act as intermediaries in the distribution of wholesale merchandise'),
  (316, 60, '999999', 'Establecimientos no clasificados (no han sido posible clasificar)', 'Unclassified establishments (not possible to classify)');

-- Reset sequences
SELECT setval(pg_get_serial_sequence('sector', 'id'), (SELECT MAX(id) FROM sector));
SELECT setval(pg_get_serial_sequence('category', 'id'), (SELECT MAX(id) FROM category));
SELECT setval(pg_get_serial_sequence('activity', 'id'), (SELECT MAX(id) FROM activity));

-- ---- FK update on empresas_incorporaciones ----
-- Run after confirming migration:
-- ALTER TABLE empresas_incorporaciones
--     DROP CONSTRAINT IF EXISTS empresas_incorporaciones_activity_id_fkey,
--     ADD  CONSTRAINT empresas_incorporaciones_activity_id_fkey
--          FOREIGN KEY (activity_id) REFERENCES activity(id);
